//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1._5_Consumir_Web_Service.MiServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", ConfigurationName="MiServicio.ws_last_positionSoap")]
    public interface ws_last_positionSoap {
        
        // CODEGEN: Parameter 'GetLastPositionResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bu01.utraxweb.com/WS/utrax.ws_last_position/GetLastPosition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _1._5_Consumir_Web_Service.MiServicio.GetLastPositionResponse GetLastPosition(_1._5_Consumir_Web_Service.MiServicio.GetLastPositionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bu01.utraxweb.com/WS/utrax.ws_last_position/GetLastPosition", ReplyAction="*")]
        System.Threading.Tasks.Task<_1._5_Consumir_Web_Service.MiServicio.GetLastPositionResponse> GetLastPositionAsync(_1._5_Consumir_Web_Service.MiServicio.GetLastPositionRequest request);
        
        // CODEGEN: Parameter 'GetLastPosition_02Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bu01.utraxweb.com/WS/utrax.ws_last_position/GetLastPosition_02", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Response GetLastPosition_02(_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bu01.utraxweb.com/WS/utrax.ws_last_position/GetLastPosition_02", ReplyAction="*")]
        System.Threading.Tasks.Task<_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Response> GetLastPosition_02Async(_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Request request);
        
        // CODEGEN: Parameter 'GetLastPosition_03Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bu01.utraxweb.com/WS/utrax.ws_last_position/GetLastPosition_03", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Response GetLastPosition_03(_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bu01.utraxweb.com/WS/utrax.ws_last_position/GetLastPosition_03", ReplyAction="*")]
        System.Threading.Tasks.Task<_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Response> GetLastPosition_03Async(_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/")]
    public partial class InfoLastPosition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eCodeField;
        
        private string platesField;
        
        private string device_IdField;
        
        private string instance_IdField;
        
        private string eventoField;
        
        private string dateTime_GPSField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string speedField;
        
        private string courseField;
        
        private string orientationField;
        
        private string referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string eCode {
            get {
                return this.eCodeField;
            }
            set {
                this.eCodeField = value;
                this.RaisePropertyChanged("eCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Plates {
            get {
                return this.platesField;
            }
            set {
                this.platesField = value;
                this.RaisePropertyChanged("Plates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Device_Id {
            get {
                return this.device_IdField;
            }
            set {
                this.device_IdField = value;
                this.RaisePropertyChanged("Device_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Instance_Id {
            get {
                return this.instance_IdField;
            }
            set {
                this.instance_IdField = value;
                this.RaisePropertyChanged("Instance_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Evento {
            get {
                return this.eventoField;
            }
            set {
                this.eventoField = value;
                this.RaisePropertyChanged("Evento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DateTime_GPS {
            get {
                return this.dateTime_GPSField;
            }
            set {
                this.dateTime_GPSField = value;
                this.RaisePropertyChanged("DateTime_GPS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
                this.RaisePropertyChanged("Speed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Course {
            get {
                return this.courseField;
            }
            set {
                this.courseField = value;
                this.RaisePropertyChanged("Course");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Orientation {
            get {
                return this.orientationField;
            }
            set {
                this.orientationField = value;
                this.RaisePropertyChanged("Orientation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/")]
    public partial class InfoLastPosition_02 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eCodeField;
        
        private string platesField;
        
        private string device_IdField;
        
        private string instance_IdField;
        
        private string eventoField;
        
        private string dateTime_GPSField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string speedField;
        
        private string courseField;
        
        private string orientationField;
        
        private string odometerField;
        
        private string ignitionField;
        
        private string referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string eCode {
            get {
                return this.eCodeField;
            }
            set {
                this.eCodeField = value;
                this.RaisePropertyChanged("eCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Plates {
            get {
                return this.platesField;
            }
            set {
                this.platesField = value;
                this.RaisePropertyChanged("Plates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Device_Id {
            get {
                return this.device_IdField;
            }
            set {
                this.device_IdField = value;
                this.RaisePropertyChanged("Device_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Instance_Id {
            get {
                return this.instance_IdField;
            }
            set {
                this.instance_IdField = value;
                this.RaisePropertyChanged("Instance_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Evento {
            get {
                return this.eventoField;
            }
            set {
                this.eventoField = value;
                this.RaisePropertyChanged("Evento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DateTime_GPS {
            get {
                return this.dateTime_GPSField;
            }
            set {
                this.dateTime_GPSField = value;
                this.RaisePropertyChanged("DateTime_GPS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
                this.RaisePropertyChanged("Speed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Course {
            get {
                return this.courseField;
            }
            set {
                this.courseField = value;
                this.RaisePropertyChanged("Course");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Orientation {
            get {
                return this.orientationField;
            }
            set {
                this.orientationField = value;
                this.RaisePropertyChanged("Orientation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Odometer {
            get {
                return this.odometerField;
            }
            set {
                this.odometerField = value;
                this.RaisePropertyChanged("Odometer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Ignition {
            get {
                return this.ignitionField;
            }
            set {
                this.ignitionField = value;
                this.RaisePropertyChanged("Ignition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastPosition", WrapperNamespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", IsWrapped=true)]
    public partial class GetLastPositionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", Order=2)]
        public string Page;
        
        public GetLastPositionRequest() {
        }
        
        public GetLastPositionRequest(string User, string Password, string Page) {
            this.User = User;
            this.Password = Password;
            this.Page = Page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastPositionResponse", WrapperNamespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", IsWrapped=true)]
    public partial class GetLastPositionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public _1._5_Consumir_Web_Service.MiServicio.InfoLastPosition[] GetLastPositionResult;
        
        public GetLastPositionResponse() {
        }
        
        public GetLastPositionResponse(_1._5_Consumir_Web_Service.MiServicio.InfoLastPosition[] GetLastPositionResult) {
            this.GetLastPositionResult = GetLastPositionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastPosition_02", WrapperNamespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", IsWrapped=true)]
    public partial class GetLastPosition_02Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", Order=2)]
        public string Page;
        
        public GetLastPosition_02Request() {
        }
        
        public GetLastPosition_02Request(string User, string Password, string Page) {
            this.User = User;
            this.Password = Password;
            this.Page = Page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastPosition_02Response", WrapperNamespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", IsWrapped=true)]
    public partial class GetLastPosition_02Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public _1._5_Consumir_Web_Service.MiServicio.InfoLastPosition_02[] GetLastPosition_02Result;
        
        public GetLastPosition_02Response() {
        }
        
        public GetLastPosition_02Response(_1._5_Consumir_Web_Service.MiServicio.InfoLastPosition_02[] GetLastPosition_02Result) {
            this.GetLastPosition_02Result = GetLastPosition_02Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastPosition_03", WrapperNamespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", IsWrapped=true)]
    public partial class GetLastPosition_03Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", Order=2)]
        public string Page;
        
        public GetLastPosition_03Request() {
        }
        
        public GetLastPosition_03Request(string User, string Password, string Page) {
            this.User = User;
            this.Password = Password;
            this.Page = Page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastPosition_03Response", WrapperNamespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", IsWrapped=true)]
    public partial class GetLastPosition_03Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bu01.utraxweb.com/WS/utrax.ws_last_position/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public _1._5_Consumir_Web_Service.MiServicio.InfoLastPosition_02[] GetLastPosition_03Result;
        
        public GetLastPosition_03Response() {
        }
        
        public GetLastPosition_03Response(_1._5_Consumir_Web_Service.MiServicio.InfoLastPosition_02[] GetLastPosition_03Result) {
            this.GetLastPosition_03Result = GetLastPosition_03Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ws_last_positionSoapChannel : _1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ws_last_positionSoapClient : System.ServiceModel.ClientBase<_1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap>, _1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap {
        
        public ws_last_positionSoapClient() {
        }
        
        public ws_last_positionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ws_last_positionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_last_positionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_last_positionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1._5_Consumir_Web_Service.MiServicio.GetLastPositionResponse _1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap.GetLastPosition(_1._5_Consumir_Web_Service.MiServicio.GetLastPositionRequest request) {
            return base.Channel.GetLastPosition(request);
        }
        
        public _1._5_Consumir_Web_Service.MiServicio.InfoLastPosition[] GetLastPosition(string User, string Password, string Page) {
            _1._5_Consumir_Web_Service.MiServicio.GetLastPositionRequest inValue = new _1._5_Consumir_Web_Service.MiServicio.GetLastPositionRequest();
            inValue.User = User;
            inValue.Password = Password;
            inValue.Page = Page;
            _1._5_Consumir_Web_Service.MiServicio.GetLastPositionResponse retVal = ((_1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap)(this)).GetLastPosition(inValue);
            return retVal.GetLastPositionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_1._5_Consumir_Web_Service.MiServicio.GetLastPositionResponse> _1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap.GetLastPositionAsync(_1._5_Consumir_Web_Service.MiServicio.GetLastPositionRequest request) {
            return base.Channel.GetLastPositionAsync(request);
        }
        
        public System.Threading.Tasks.Task<_1._5_Consumir_Web_Service.MiServicio.GetLastPositionResponse> GetLastPositionAsync(string User, string Password, string Page) {
            _1._5_Consumir_Web_Service.MiServicio.GetLastPositionRequest inValue = new _1._5_Consumir_Web_Service.MiServicio.GetLastPositionRequest();
            inValue.User = User;
            inValue.Password = Password;
            inValue.Page = Page;
            return ((_1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap)(this)).GetLastPositionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Response _1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap.GetLastPosition_02(_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Request request) {
            return base.Channel.GetLastPosition_02(request);
        }
        
        public _1._5_Consumir_Web_Service.MiServicio.InfoLastPosition_02[] GetLastPosition_02(string User, string Password, string Page) {
            _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Request inValue = new _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Request();
            inValue.User = User;
            inValue.Password = Password;
            inValue.Page = Page;
            _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Response retVal = ((_1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap)(this)).GetLastPosition_02(inValue);
            return retVal.GetLastPosition_02Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Response> _1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap.GetLastPosition_02Async(_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Request request) {
            return base.Channel.GetLastPosition_02Async(request);
        }
        
        public System.Threading.Tasks.Task<_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Response> GetLastPosition_02Async(string User, string Password, string Page) {
            _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Request inValue = new _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_02Request();
            inValue.User = User;
            inValue.Password = Password;
            inValue.Page = Page;
            return ((_1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap)(this)).GetLastPosition_02Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Response _1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap.GetLastPosition_03(_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Request request) {
            return base.Channel.GetLastPosition_03(request);
        }
        
        public _1._5_Consumir_Web_Service.MiServicio.InfoLastPosition_02[] GetLastPosition_03(string User, string Password, string Page) {
            _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Request inValue = new _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Request();
            inValue.User = User;
            inValue.Password = Password;
            inValue.Page = Page;
            _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Response retVal = ((_1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap)(this)).GetLastPosition_03(inValue);
            return retVal.GetLastPosition_03Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Response> _1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap.GetLastPosition_03Async(_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Request request) {
            return base.Channel.GetLastPosition_03Async(request);
        }
        
        public System.Threading.Tasks.Task<_1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Response> GetLastPosition_03Async(string User, string Password, string Page) {
            _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Request inValue = new _1._5_Consumir_Web_Service.MiServicio.GetLastPosition_03Request();
            inValue.User = User;
            inValue.Password = Password;
            inValue.Page = Page;
            return ((_1._5_Consumir_Web_Service.MiServicio.ws_last_positionSoap)(this)).GetLastPosition_03Async(inValue);
        }
    }
}
